from __future__ import annotations

from html.parser import HTMLParser
from pathlib import Path
import re
import unittest


ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "web" / "all-things-agentic.html"


class _PageContract(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ids: list[str] = []
        self.labels: dict[str, str] = {}
        self.attributes: dict[str, dict[str, str | None]] = {}
        self.external_sources: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = dict(attrs)
        element_id = values.get("id")
        if element_id:
            self.ids.append(element_id)
            self.attributes[element_id] = values
        if tag == "label" and values.get("for"):
            self.labels[str(values["for"])] = values.get("for") or ""
        for name in ("src", "href"):
            value = values.get(name)
            if value and re.match(r"^(?:https?:)?//", value):
                self.external_sources.append(value)


class AllThingsAgenticUiTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.html = PAGE.read_text(encoding="utf-8")
        cls.parser = _PageContract()
        cls.parser.feed(cls.html)

    def test_legacy_access_and_job_controls_remain_unique_and_labeled(self) -> None:
        required = {
            "access",
            "message",
            "submit",
            "cancel",
            "retry",
            "error",
            "state",
            "stage",
            "progress",
            "bar",
            "eta",
            "job",
            "brief",
        }
        self.assertTrue(required.issubset(self.parser.ids))
        for element_id in required:
            self.assertEqual(self.parser.ids.count(element_id), 1, element_id)
        self.assertIn("access", self.parser.labels)
        self.assertIn("message", self.parser.labels)
        access = self.parser.attributes["access"]
        self.assertEqual(access["type"], "password")
        self.assertEqual(access["autocomplete"], "off")
        self.assertEqual(access["maxlength"], "256")

    def test_storyboard_timeline_is_truthful_plan_only_and_self_contained(self) -> None:
        for marker in (
            'id="conversationFeed"',
            'id="timelineDock"',
            'id="timelineViewport"',
            'id="timelineTrack"',
            'id="timelinePlayhead"',
            'id="timelineSelection"',
            "Shot list · source-aware rough-cut EDL",
            "Planned non-drop 24 fps",
            "No footage has been selected, changed, or rendered.",
            "no source clip has been selected or mutated",
            "@media(max-width:980px)",
            "overflow-x:auto",
        ):
            self.assertIn(marker, self.html)
        self.assertEqual(self.parser.external_sources, [])
        self.assertNotIn("duration_seconds /", self.html)
        self.assertIn("clip.dataset.sceneNumber = String(shot.scene_number)", self.html)
        self.assertIn("clip.dataset.shotId = String(shot.shot_id)", self.html)
        self.assertIn("shot.planned_in_timecode", self.html)
        self.assertIn("shot.planned_out_timecode", self.html)
        self.assertIn("card.framing", self.html)
        self.assertIn("card.camera", self.html)
        self.assertIn("card.action", self.html)

    def test_package_json_download_is_local_sanitized_and_revoked(self) -> None:
        for marker in (
            'id="downloadPackage"',
            "function downloadStoryboardPackage()",
            "JSON.stringify(currentStoryboardPackage, null, 2)",
            "{type:'application/json'}",
            "URL.createObjectURL(blob)",
            "link.download = packageFilename()",
            "URL.revokeObjectURL(url)",
            "-storyboard-edl.json",
            ".replace(/[^a-z0-9]+/gi, '-')",
            "renderStoryboardPackage(null)",
        ):
            self.assertIn(marker, self.html)
        download_body = self.html.split("function downloadStoryboardPackage()", 1)[1].split(
            "function responseError", 1
        )[0]
        self.assertNotIn("access", download_body.casefold())

    def test_detailed_production_sheet_is_escaped_compact_and_plan_only(self) -> None:
        for marker in (
            'id="downloadDetailedSheet"',
            "Detailed production sheet HTML",
            "function detailedProductionSheetHtml()",
            "function downloadDetailedProductionSheet()",
            "{type:'text/html;charset=utf-8'}",
            "detailedProductionSheetFilename()",
            "-detailed-production-sheet.html",
            "Content-Security-Policy",
            "default-src 'none'",
            "PLAN ONLY · NO RENDERED MEDIA",
            "Target Final Deliverables — not generated by this plan-only build.",
            "Creative direction",
            "Planned storyboard cards",
            "Deterministic audit",
            "Source-footage guidance",
            "Bridge guidance:",
            "esc(brief.title",
            "esc(brief.summary",
            "esc(brief.visual_direction",
            "esc(brief.audio_direction",
            "esc(shot?.planned_in_timecode",
            "esc(shot?.planned_out_timecode",
            "esc(card.framing",
            "esc(card.camera",
            "esc(card.action",
            "esc(card.dialogue_or_audio",
            "esc(card.source_footage_guidance",
            "esc(card.bridge_shot_guidance",
            "items.map(value => `<li>${esc(value)}</li>`)",
            "esc(check?.evidence",
            "allowlisted fields",
            "@page{size:letter portrait",
            "break-inside:auto",
        ):
            self.assertIn(marker, self.html)
        sheet_body = self.html.split("function detailedProductionSheetHtml()", 1)[1].split(
            "function visualStoryboardHtml()", 1
        )[0]
        self.assertNotIn("JSON.stringify", sheet_body)
        self.assertNotIn("fetch(", sheet_body)
        self.assertNotIn("access", sheet_body.casefold())
        self.assertNotIn("secret", sheet_body.casefold())
        self.assertNotIn("<script", sheet_body.casefold())
        self.assertNotIn("break-inside:avoid", sheet_body)

    def test_visual_storyboard_is_validated_hydrated_privately_and_grouped_for_landscape_pdf(self) -> None:
        for marker in (
            'id="downloadVisualStoryboard"',
            'id="printVisualStoryboard"',
            "Visual storyboard HTML",
            "Print / Save PDF",
            "function normalizeVisualStoryboard(value, shots)",
            "video-studio.visual-storyboard/v1",
            "technical_asset_integrity_only",
            "inline_base64",
            "private_artifact_route",
            "const rendererKeys = ['provider','framework','model','location','evidence_origin']",
            "held_for_clarification",
            "renderer_not_configured",
            "provider_blocked",
            "generation_failed",
            "invalid_provider_asset",
            "panel_limit_reached",
            "inline_budget_exhausted",
            "quota_or_rate_limited",
            "panel.mime_type !== 'image/jpeg'",
            "panel.width !== 768",
            "panel.height !== 432",
            "base64DecodedLength(panel.data_base64) === panel.byte_length",
            "panel.data_base64.startsWith('/9j/')",
            "panel.data_url || (typeof panel.data_base64 === 'string'",
            "Generated planning illustration · human visual review required",
            "Visual pending",
            "function visualStoryboardHtml()",
            "img-src data:",
            "for (let index = 0; index < entries.length; index += 6)",
            "grid-template-columns:repeat(3,minmax(0,1fr))",
            "grid-template-rows:repeat(2,2.64in)",
            "@page{size:letter landscape",
            "height:7.9in",
            "height:5.35in",
            "flex-direction:row",
            "page-break-after:always",
            "function printVisualStoryboard()",
            "printWindow.document.write(sheet)",
            "printWindow.print()",
            "-visual-storyboard.html",
        ):
            self.assertIn(marker, self.html)
        visual_body = self.html.split("function visualStoryboardHtml()", 1)[1].split(
            "function responseError", 1
        )[0]
        self.assertNotIn("fetch(", visual_body)
        self.assertNotIn("access", visual_body.casefold())
        self.assertNotIn("secret", visual_body.casefold())
        self.assertNotIn("<script", visual_body.casefold())
        self.assertNotIn("https://", visual_body.casefold())
        self.assertNotIn("http://", visual_body.casefold())
        self.assertIn("URL.revokeObjectURL(url)", visual_body)

        private_media_body = self.html.split("function privateArtifactPath(jobId, artifactId)", 1)[1].split(
            "function visualPanelEntries", 1
        )[0]
        for marker in (
            "`/v1/jobs/${encodeURIComponent(jobId)}/artifacts/${encodeURIComponent(artifactId)}`",
            "'X-Video-Studio-Access':$('access').value",
            "blob.type !== expectedType || blob.size !== artifact.byte_length",
            "job.state !== 'succeeded'",
            "visual.representation !== 'private_artifact_route'",
            "visual.status !== 'complete'",
            "for (const panel of visual.panels)",
            "panel.data_url = await blobDataUrl(blob)",
            "privateArtifactBlob(job.job_id, pitch.video, 'video/mp4')",
            "currentPitchVideoUrl = URL.createObjectURL(videoBlob)",
        ):
            self.assertIn(marker, private_media_body)
        self.assertNotIn("artifact.object_name", private_media_body)

    def test_same_origin_job_and_access_contract_is_unchanged(self) -> None:
        for marker in (
            "'X-Video-Studio-Access':$('access').value",
            "request('/v1/jobs', {method:'POST', body:JSON.stringify({message})})",
            "request(`/v1/jobs/${currentJob.job_id}`)",
            "request(`/v1/jobs/${currentJob.job_id}:cancel`, {method:'POST', body:'{}'})",
            "request(`/v1/jobs/${currentJob.job_id}:retry`, {method:'POST', body:'{}'})",
            "const terminal = new Set(['succeeded', 'failed', 'cancelled'])",
            "setTimeout(poll, 1200)",
        ):
            self.assertIn(marker, self.html)
        self.assertNotIn("localStorage", self.html)
        self.assertNotIn("sessionStorage", self.html)

    def test_owner_v2_has_real_pwa_access_attachment_and_editorial_controls(self) -> None:
        required_ids = {
            "installApp",
            "attachmentButton",
            "attachmentMenu",
            "attachStory",
            "attachFootage",
            "scriptFile",
            "footageFiles",
            "sourceSummary",
            "animatic",
            "animaticPlay",
            "animaticStop",
            "pitchVideo",
            "downloadPitchVideo",
        }
        self.assertTrue(required_ids.issubset(self.parser.ids))
        for marker in (
            "Video Studio Storyboard Artist &amp; Production Planner",
            'rel="manifest" href="/manifest.webmanifest"',
            "beforeinstallprompt",
            "appinstalled",
            "deferredInstallPrompt",
            "await prompt.prompt()",
            "navigator.serviceWorker.register('/sw.js')",
            "Edge open ⋯ → Apps → Install Video Studio",
            "Provided with the submission",
            "if (!$('access').value.trim())",
            "The private judge / owner access code is missing or incorrect.",
            "PDF, TXT, Markdown, Fountain, or Final Draft XML",
            "await import('/vendor/pdfjs/pdf.mjs')",
            "pdf.worker.mjs",
            "isEvalSupported: false",
            "item.hasEOL === true",
            "beginning_middle_end_excerpt",
            "Included source characters:",
            "extracted characters included",
            "Sources within the displayed bound use full text; oversized sources use disclosed beginning/middle/end excerpts.",
            "MAX_SCRIPT_CHARS = 147000",
            "MAX_COMPOSED_MESSAGE_CHARS = 159000",
            "raw bytes stay in this browser",
            "no footage-content analysis occurs",
            "function shotListCsv()",
            "function sourceAwareEdlCsv()",
            "source_duration_deficit_seconds",
            "SOURCE TOO SHORT - ADD COVERAGE OR RETIME",
            "downloadable 1920×1080 MP4 with every visual card",
        ):
            self.assertIn(marker, self.html)
        submit = self.parser.attributes["submit"]
        self.assertIn("disabled", submit)
        access_sensitive_exports = self.html.split("function shotListCsv()", 1)[1].split(
            "function storyboardSheetList", 1
        )[0]
        self.assertNotIn("$('access')", access_sensitive_exports)

    def test_deadline_ui_polish_is_compact_clear_and_accessible(self) -> None:
        for marker in (
            'class="workflow-strip" aria-label="Production planning workflow"',
            '<span aria-hidden="true">1</span>Describe',
            '<span aria-hidden="true">2</span>Brief',
            '<span aria-hidden="true">3</span>Plan',
            '<span aria-hidden="true">4</span>Storyboard',
            '<span aria-hidden="true">5</span>Review / Export',
            'class="capability-nav" aria-label="Included Video Studio planning capabilities"',
            '<span class="capability-label">Includes</span>',
            'class="capability-chip"',
            "textarea:focus-visible{outline:2px solid var(--amber-bright)",
            'Judge / owner access code — provided with submission',
            'id="submit" class="primary" type="button" disabled>Create production plan</button>',
            "main{padding-top:24px}.hero{padding:4px 2px 18px}",
        ):
            self.assertIn(marker, self.html)
        self.assertNotIn("hero-note", self.html)
        self.assertNotIn("Build scene package", self.html)
        self.assertNotIn("before the scene package is ready", self.html)
        self.assertNotIn("The scene package for", self.html)
        self.assertNotIn('class="capability-nav" aria-label="Jump to', self.html)

    def test_contest_scope_is_visibly_truthful(self) -> None:
        for marker in (
            "planning illustrations, a timed animatic, and the narrated storyboard MP4 are previsualization",
            "not finished filmed footage",
            "generates every storyboard card and a natural Google Cloud narrated 1920×1080 pitch video only after the all-card completion gate passes",
            "Actor lip sync, final scene rendering, and applied footage editing remain Local edition quality gates.",
            "The browser voice control is a secondary device-only fallback, never the completion proof or exported production track.",
            "editorial instructions only",
            "NO FINISHED FILM FOOTAGE",
        ):
            self.assertIn(marker, self.html)

    def test_primary_pitch_requires_complete_verified_cloud_mp4_and_all_private_visuals(self) -> None:
        for marker in (
            'id="downloadPitchVideo" type="button" disabled',
            'id="pitchVideo" class="hidden" controls preload="metadata" playsinline',
            "video-studio.narrated-pitch/v1",
            "value.status !== 'complete'",
            "value.card_count !== expectedCards || value.cue_count !== expectedCards",
            "validPrivateArtifact(value.video, 'video/mp4')",
            "validPrivateArtifact(value.narration_text, 'text/plain; charset=utf-8')",
            "validPrivateArtifact(value.subtitles, 'application/x-subrip')",
            "isSha256(value.manifest_sha256)",
            "value.video.width !== 1920 || value.video.height !== 1080",
            "value.video.video_codec !== 'h264' || value.video.audio_codec !== 'aac'",
            "value.voice.provider !== 'Google Cloud Text-to-Speech'",
            "String(value.voice.model || '').includes('Chirp 3')",
            "String(value.voice.name || '').includes('Chirp3-HD')",
            "value.voice.segment_count !== expectedCards",
            "value.verification.status !== 'passed'",
            "value.verification.video_stream_count !== 1",
            "value.verification.audio_stream_count !== 1",
            "if (!visual || visual.representation !== 'private_artifact_route' || visual.status !== 'complete' || !pitch) return",
            "The natural Google Cloud narration and MP4 appear only after every visual card passes the completion gate.",
            "verified 1920×1080 H.264/AAC MP4 ready for owner review",
            "function downloadPitchVideo()",
            "-narrated-storyboard-pitch.mp4",
        ):
            self.assertIn(marker, self.html)
        self.assertIn("download.disabled = !ready", self.html)
        self.assertIn("const ready = Boolean(currentPitchPreview && currentPitchVideoUrl)", self.html)

    def test_browser_voice_is_a_secondary_natural_english_fallback(self) -> None:
        for marker in (
            'id="pitchVoiceStatus" class="pitch-disclosure" aria-live="polite"',
            ">Browser voice fallback</button>",
            "Natural pitch voice unavailable in this browser.",
            "download the pitch narration script instead",
            "function naturalPitchVoiceScore(voice)",
            "/\\b(?:natural|neural)\\b/i.test(name)",
            "if (!language.startsWith('en-') && language !== 'en') return -1",
            "function selectNaturalPitchVoice()",
            "utterance.voice = pitchVoice",
            "utterance.lang = pitchVoice.lang",
            "window.speechSynthesis?.addEventListener?.('voiceschanged', refreshPitchVoiceSelection)",
            "buildPitchCues('export')",
            "buildPitchCues('playback')",
            "Complete deterministic text export:",
            "no card text was truncated or omitted",
            "QUALIFIED NATURAL/NEURAL BROWSER VOICE",
        ):
            self.assertIn(marker, self.html)
        self.assertIn("if (currentPitchPreview) {", self.html)
        self.assertIn("$('pitchPlay').textContent = 'Cloud voice in MP4'", self.html)
        self.assertIn("$('pitchPlay').disabled = true", self.html)
        self.assertIn("$('pitchPlay').disabled = !hasPlan || !naturalVoiceReady || pitchPlaying", self.html)
        self.assertIn("$('downloadPitchScript').disabled = !hasPlan", self.html)
        self.assertNotIn("return typeof window !== 'undefined' && typeof window.SpeechSynthesisUtterance", self.html)
        self.assertNotIn("(?:natural|neural|online|premium)", self.html)

    def test_clarification_followups_are_composed_in_memory_without_extra_api_fields(self) -> None:
        for marker in (
            'id="conversationContext"',
            "let clarificationSession = null",
            "function composeClarificationSubmission(shortAnswer)",
            "Original user request:",
            "Earlier answered clarification rounds:",
            "Current clarification questions:",
            "User\\'s current short answer:",
            "answeredRounds: [",
            "...clarificationSession.answeredRounds",
            "if (brief.ready_for_production === true)",
            "clarificationSession = null",
            "addConversationMessage('user', visibleMessage)",
            "JSON.stringify({message})",
            "no server-side chat memory",
        ):
            self.assertIn(marker, self.html)
        self.assertNotIn("JSON.stringify({message,", self.html)
        self.assertNotIn("conversation_id", self.html)
        self.assertNotIn("chat_history", self.html)

    def test_job_shaped_non_2xx_response_remains_renderable_for_retry(self) -> None:
        for marker in (
            "function responseError(payload, status)",
            "if (payload && payload.job_id) error.job = payload",
            "if (error.job) render(error.job)",
            "`${detail.code || 'Job failed'} (${detail.type || `HTTP ${status}`})`",
        ):
            self.assertIn(marker, self.html)
        self.assertNotIn("new Error(payload.error", self.html)

    def test_progress_and_status_are_accessible_without_invented_eta(self) -> None:
        progress = self.parser.attributes["progressBar"]
        self.assertEqual(progress["role"], "progressbar")
        self.assertEqual(progress["aria-valuemin"], "0")
        self.assertEqual(progress["aria-valuemax"], "100")
        self.assertIn("$('progressBar').setAttribute('aria-valuenow', String(progress))", self.html)
        self.assertIn("ETA unavailable until a real completed-job timing sample exists.", self.html)
        self.assertIn("eta.sample_count", self.html)


if __name__ == "__main__":
    unittest.main()
